[package]
name = "ghost_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = { version = "0.10.1", features = ["std", "stream", "zeroize"] }
log = "0.4.17"
rand = "0.8.5"
sha2 = "0.10.6"
stderrlog = "0.5.4"

[[bin]]
name = "ghost_shell_server"
path = "src/server.rs"

[[bin]]
name = "ghost_shell_client"
path = "src/client.rs"
